#!/bin/bash

cd "`dirname "$0"`/.."

if [ ${#@} -ne 1 ]; then
	echo
	echo `basename "$0"` width
	echo
	exit
fi

PATH=$PWD/bin:$PATH
let width="$1"
echo using convolution width $width >&2
cons "$width" | w min max | r min | min "$width" | cons "$width" | avg "$width" | w l | r max | max "$width" | cons "$width" | avg "$width" | w r | mux l r
